name: 'SafeJourney Checker'
description: 'Check Swift code for SafeJourney pattern violations to ensure thread safety'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  path:
    description: 'Path to check for violations (directory or file)'
    required: false
    default: 'Sources/'
  fail-on-error:
    description: 'Fail the action if errors are found'
    required: false
    default: 'true'
  fail-on-warning:
    description: 'Fail the action if warnings are found'
    required: false
    default: 'false'

outputs:
  violations-count:
    description: 'Total number of violations found'
    value: ${{ steps.check.outputs.violations-count }}
  errors-count:
    description: 'Number of error violations found'
    value: ${{ steps.check.outputs.errors-count }}
  warnings-count:
    description: 'Number of warning violations found'
    value: ${{ steps.check.outputs.warnings-count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
    
    - name: Build SafeJourney Checker
      shell: bash
      run: |
        echo "🔨 Building SafeJourney Checker..."
        swift build --product sj
        echo "✅ Checker built successfully"
    
    - name: Prepare SafeJourney Check
      shell: bash
      run: |
        echo "📋 SafeJourney enforces consistent thread safety rules for all Swift classes"
        echo "🎯 No configuration needed - the pattern works best when applied universally"
    
    - name: Run SafeJourney Check
      shell: bash
      id: check
      run: |
        echo "🔍 Running SafeJourney pattern check..."
        echo "🎯 Target path: ${{ inputs.path }}"
        
        # Run the built checker using swift run
        CMD="swift run sj ${{ inputs.path }}"
        echo "⚡ Running: $CMD"
        
        # Run the checker and capture output
        if output=$($CMD 2>&1); then
          echo "✅ No violations found!"
          echo "violations-count=0" >> $GITHUB_OUTPUT
          echo "errors-count=0" >> $GITHUB_OUTPUT
          echo "warnings-count=0" >> $GITHUB_OUTPUT
          exit 0
        else
          exit_code=$?
          echo "📊 Analysis complete. Violations found:"
          echo "$output"
          
          errors=$(echo "$output" | grep -c "❌" 2>/dev/null)
          warnings=$(echo "$output" | grep -c "⚠️" 2>/dev/null)

          # If grep did not find anything, it returns "0", but if it fails for another reason, still default to 0
          errors=${errors:-0}
          warnings=${warnings:-0}
          
          total=$((errors + warnings))
          
          echo "violations-count=$total" >> $GITHUB_OUTPUT
          echo "errors-count=$errors" >> $GITHUB_OUTPUT
          echo "warnings-count=$warnings" >> $GITHUB_OUTPUT
          
          # Determine if we should fail
          should_fail=false
          if [ "${{ inputs.fail-on-error }}" = "true" ] && [ "$errors" -gt 0 ]; then
            should_fail=true
            echo "🚨 Failing due to $errors error(s)"
          fi
          
          if [ "${{ inputs.fail-on-warning }}" = "true" ] && [ "$warnings" -gt "0" ]; then
            should_fail=true
            echo "⚠️ Failing due to $warnings warning(s)"
          fi
          
          if [ "$should_fail" = "true" ]; then
            echo "❌ Action failed due to violations"
            exit 1
          else
            echo "✅ Action passed (violations found but not failing)"
            exit 0
          fi
        fi
    
    - name: Summary
      shell: bash
      if: always()
      run: |
        echo "## 🛡️ SafeJourney Check Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Path checked:** \`${{ inputs.path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Total violations:** ${{ steps.check.outputs.violations-count }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Errors:** ${{ steps.check.outputs.errors-count }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Warnings:** ${{ steps.check.outputs.warnings-count }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.check.outputs.violations-count }}" = "0" ]; then
          echo "✅ **Result:** All checks passed! Your code follows the SafeJourney pattern perfectly." >> $GITHUB_STEP_SUMMARY
        else
          echo "📋 **Result:** Violations found. Please review and fix them for better thread safety." >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "_Generated by [SafeJourney](https://github.com/customerio/safe-journey)_" >> $GITHUB_STEP_SUMMARY
